### PR TITLE
Using serverUrl constant for batch requests.

### PR DESCRIPTION
**Pull request by peterdotjs**

### CODE REVIEW

**Comment by andrewimm** [comment]
Importing `url` seems like overkill to me.

**Comment by peterdotjs** [comment]
@andrewimm I could take strip out the parsing pieces for the path rather than use the module if you concerned about bloat.

**Comment by andrewimm** [comment]
```js
// Remove the protocol
var url = serverUrl.replace(/https?:\/\//, '');
var path = url.substr(url.indexOf('/'));
```
should work, right?

**Comment by peterdotjs** [comment]
That'll work for the current `serverUrl` config value but I'm also thinking about any corner cases that users might change the value to.

**Comment by andrewimm** [comment]
And what would those cases be? This works for urls with and without protocol. In a valid URL, slashes can only exist between the protocol and the domain, or within the path, so once the protocol is removed, the first slash is the beginning of the path. Beyond that, setting an invalid value to this will break the entire SDK anyways, so it's not unreasonable to us to say that only valid URLs are supported.

**Comment by andrewimm** [comment]
Actually, we need the "does it end with a slash?" check to make it really work. Otherwise a value like "api.parse.com" fails. Otherwise, I think it's relatively bulletproof.

**Comment by peterdotjs** [comment]
We'll need to handle the host case as well: `'http://localhost.com:8080/p/a/t/h`

**Comment by andrewimm** [comment]
@peterdotjs the code works for that:
var url = 'https://localhost.com:8080/p/a/t/h'.replace(/https?:\/\//, ''); // url = localhost.com:8080/p/a/t/h
var path = url.substr(url.indexOf('/')); // path = '/p/a/t/h'

Feel free to unit-test this thing into oblivion

**Comment by andrewimm** [comment]
My only concern is adding a 650 LOC library to do something that can be done in 1-2 lines.

**Comment by peterdotjs** [comment]
@andrewimm agreed that there are a lot of things in the lib we won't use. I'm sure there will be other cases that come up (`//foo/bar `) but this should work for most cases.

**Comment by andrewimm** [comment]
For now, treat it as a private API (it's not like anyone could have their own Parse address anyways, this is basically for our internal tests for now). If we ever publicize it, we can establish expectations and shore up the code, but immediately, I like treating it like a black box.

**Comment by andrewimm** [comment]
Also, once you land this change, I'd like to cut a release for 1.6.14, which will probably be the last one before 1.7

**Comment by peterdotjs** [comment]
Ready for merging.

**Comment by andrewimm** [comment]
LGTM, merging.

**Pull request merged**
